services:
  web:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - "5050:5050"
    environment:
      - PORT=5050
    depends_on:
      - postgresql
    restart: always

  postgresql:
    image: postgres:15-alpine
    container_name: api_postgresql
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=uzinfocom_todo
#    volumes:
#      - pgdata:/var/lib/postgresql/data

#volumes:
#  pgdata:
